### ISSUE TITLE
[IMPROVEMENTS]: 

### ISSUE THREAD

**Issue by Abysshehe** [typical-developers/oaklands-feedback#715] opened 2024-07-06 07:29 UTC
### Roblox Username

Massivepaintball232

### What do you think can have quality-of-life improvements?

Multi-Select

### How do you think things can be improved?

We should have a drag mode to select everything in the location that we want to delete. I know with a lot of builds there's a lot of small pieces that suck having to select one by one.

**Comment by HooferDevelops** [comment] 2024-07-07 20:04
Duplicate of #714

**Closed by HooferDevelops** 2024-07-07 20:04 UTC
Labels: improvement
