### ISSUE TITLE
[BUG]: Unable to load properties

### ISSUE THREAD

**Issue by KOMKO190** [typical-developers/oaklands-feedback#191] opened 2023-12-23 13:59 UTC
### Roblox Username

KOMKO190

### What version did this issue occur in?

1.45.6

### Describe the issue in detail.

I loaded my game and wanted to load a property, there were 5 players + me in the lobby and I tried circling around to see which properties were available.

Circling through them, I saw that I could only claim a certain property, but not any others (they weren't claimed).

Circling back and forth led to the game sometimes saying that a property is available but next time to tell that it's not -> there were no players during that time that occupied that property.

### Provide some images / videos of the issue in action.

**These videos will expire in 2 days (I uploaded it 13:53 GMT+1 on December 23rd) -> please download them since I can't compress 89MB to under 10** - and also why are they 89MB like wha.

https://streamable.com/3a67qf
https://streamable.com/snfodk

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by LuckFire** [comment] 2023-12-25 02:14
Duplicate of #108

**Closed by LuckFire** 2023-12-25 02:14 UTC
Labels: bug
