### ISSUE TITLE
[BUG]: Changing the color of sign text does not work

### ISSUE THREAD

**Issue by uhhhhhhhhhhhhhhhh56** [typical-developers/oaklands-feedback#229] opened 2024-03-01 00:49 UTC
### Roblox Username

uhhhhhhhhhhhhhhhh56

### What version did this issue occur in?

1.50/1.50.1

### Describe the issue in detail.

This is very much not white, this is the color for purple. This happens with every sign. Submitting the color ID in changes it back to #ffffff REGARDLESS of what you actually put. Kinda ironic that this glitch began in the QoL update. Anyways, it would be a good idea to fix this asap.

### Provide some images / videos of the issue in action.

![RobloxScreenShot20240229_194009425](https://github.com/typical-developers/oaklands-feedback/assets/161783917/47504af4-8447-4eea-b4e0-7a7ccd4b133f)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment] 2024-03-01 01:03
Duplicate of #218

**Closed by HooferDevelops** 2024-03-01 01:03 UTC
Labels: bug
