### ISSUE TITLE
[BUG]: Game wont load.

### ISSUE THREAD

**Issue by jukepilot** [typical-developers/oaklands-feedback#174] opened 2023-12-14 01:13 UTC
### Roblox Username

jukepilot

### What version did this issue occur in?

1.45.3

### Describe the issue in detail.

When I joined a fresh server, my game wouldnt load. Not much more info. 2 warnings.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/140344252/5b8a40dc-b78a-49ef-9188-b9ac6c9bdc88)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment] 2023-12-14 04:01
Duplicate of #90.

**Closed by HooferDevelops** 2023-12-14 04:01 UTC
Labels: bug
