### ISSUE TITLE
[BUG]: Item fling upon unanchor 

### ISSUE THREAD

**Issue by hokies4life06** [typical-developers/oaklands-feedback#228] opened 2024-02-29 17:05 UTC
### Roblox Username

hokies4life06

### What version did this issue occur in?

1.50.1

### Describe the issue in detail.

So my meteor core got flung when I touched it, I got my alt on and it was in same place it was when it got flung for my alt, I used my alt to touch it, it then reappeared where it was previously before being flung. The meteor core images are from my main account/alt accounts perspectives.

### Provide some images / videos of the issue in action.

![3f69548d-6579-402c-b0e7-6aa6dd512313](https://github.com/typical-developers/oaklands-feedback/assets/161747942/3aa5a30f-3ecd-4cc5-a824-8973439f9d3c)
![IMG_1710](https://github.com/typical-developers/oaklands-feedback/assets/161747942/a678f52a-ec6d-46dc-948b-3d3684d51444)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment] 2024-04-19 18:19
Duplicate of #9

**Closed by HooferDevelops** 2024-04-19 18:19 UTC
Labels: bug
