### ISSUE TITLE
[BUG]: When joining a full server, it shows that all plots are claimed (even though one is always not) and i am unable to claim a plot

### ISSUE THREAD

**Issue by JJJustMax** [typical-developers/oaklands-feedback#212] opened 2024-02-08 14:39 UTC
### Roblox Username

JJJustMax

### What version did this issue occur in?

1.48.0

### Describe the issue in detail.

When joining a full server, it shows that all plots are claimed (even though one is always not) and i am unable to claim a plot at all. 
Only happens in full servers

### Provide some images / videos of the issue in action.

didn't screenshot it in time, it fixes itself when rejoining though

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by LuckFire** [comment] 2024-02-08 20:14
Duplicate of #108

**Closed** 2024-02-08 20:15 UTC
Labels: bug, duplicate
