### ISSUE TITLE
[BUG]: Arms look weird in driver seat 

### ISSUE THREAD

**Issue by livphobia** [typical-developers/oaklands-feedback#680] opened 2024-06-29 23:03 UTC
### Roblox Username

livphobia

### What version did this issue occur in?

1.60.1

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/174218096/dc2c49c2-e36b-4c77-9288-a93071294946)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment] 2024-06-30 21:37
Duplicate of #674

**Closed by HooferDevelops** 2024-06-30 21:37 UTC
Labels: bug
