### ISSUE TITLE
[BUG]: despawning items

### ISSUE THREAD

**Issue by Embersawitch** [typical-developers/oaklands-feedback#201] opened 2024-01-12 02:48 UTC
### Roblox Username

Embersawitch

### What version did this issue occur in?

1.45.7

### Describe the issue in detail.

My lantern and a jar of fireflies despawn. I used them as decor and had them anchored on a cube I made into a shelf, I unanchored them and then tried to drag them, as soon as I pressed drag they disappeared. The lantern happened first but I figured it was a fluke, then about 2 minutes or so later I tried to move the jar. I logged off and back on hoping that they would be there but they were gone. This has been happening for the past 2 days or so. I have not been able to report it until now. I tried to pick up a meteorite off a cliff where the big cave is for the quest for fire axe & it disappeared as soon as I pressed drag. Idc about the items but I am too afraid to move the stuff I want to keep now.

### Provide some images / videos of the issue in action.

I don't have any video or photo, I play on mobile and if I try to get recorder up when glitch happens it shuts my game off after a few seconds.

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment] 2024-04-19 18:15
Duplicate of #9

**Closed by HooferDevelops** 2024-04-19 18:15 UTC
Labels: bug
