### ISSUE TITLE
[BUG]: truck with trailer speed glitch 

### ISSUE THREAD

**Issue by agentluca** [typical-developers/oaklands-feedback#80] opened 2023-09-30 22:39 UTC
### Roblox Username

agent_luca

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

i have 4 trailers and found an glitch by accident 
i just unhitch and hitch again and the car just drives like there is no trailer i dont rlly know how to explain

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/113304551/f051f553-c9a1-49c8-afe7-b919c401d8e3)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Imjustjokingwithya** [comment] 2023-10-01 05:20
Duplicate of #39

**Closed** 2023-10-25 23:58 UTC
Labels: bug, fixed in later
