### ISSUE TITLE
[BUG]: raw wood removal

### ISSUE THREAD

**Issue by kaip0v** [typical-developers/oaklands-feedback#170] opened 2023-12-11 13:09 UTC
### Roblox Username

kaip0v

### What version did this issue occur in?

1.45.0

### Describe the issue in detail.

realized that all meteorites were turned into Santa gifts at this event and went to buy them en masse from NPCs, a total of 5-6 gifts, all additional items remained, and the trees disappeared from the base as they were not recycled.
this is not the first time, but last time I put up with it and did not write a bug report, now when 10+ event trees disappeared I couldn't stand it anymore and decided to write a bug report.
Please get this fixed.
there's only one screenshot where there was at least some number of them, and one when I logged on to the private server again.

### Provide some images / videos of the issue in action.

![RobloxScreenShot20231211_142645097](https://github.com/typical-developers/oaklands-feedback/assets/93764011/a544660b-84d9-4d79-bfff-0dc7d494c895)
![RobloxScreenShot20231211_155819111](https://github.com/typical-developers/oaklands-feedback/assets/93764011/7424885b-35d1-4f8d-bd38-8afee45ac9b1)

### Before Submitting

- [x] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by kaip0v** [comment] 2023-12-11 13:16
p.s.
I also restarted on the same server from where I left, they did not stay on the server, but disappeared along with my base, and when loading did not appear again

**Comment by HooferDevelops** [comment] 2023-12-12 05:41
I am struggling to understand what this bug report is about.

**Comment by kaip0v** [comment] 2023-12-13 07:55
> I am struggling to understand what this bug report is about.

[video](https://www.youtube.com/watch?v=PsdjuQKDomo)
0:10 - saved wood on base
2:10 - it's already missing from the base

**Comment by HooferDevelops** [comment] 2023-12-14 04:00
Duplicate of #164

**Closed** 2023-12-14 04:00 UTC
Labels: bug, duplicate
